# coding: utf-8

"""
    YNAB API Endpoints

    Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import ynab_api
from ynab_api.models.budget_detail_all_of import BudgetDetailAllOf  # noqa: E501
from ynab_api.rest import ApiException

class TestBudgetDetailAllOf(unittest.TestCase):
    """BudgetDetailAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BudgetDetailAllOf
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = ynab_api.models.budget_detail_all_of.BudgetDetailAllOf()  # noqa: E501
        if include_optional :
            return BudgetDetailAllOf(
                accounts = [
                    ynab_api.models.account.Account(
                        id = '0', 
                        name = '0', 
                        type = 'checking', 
                        on_budget = True, 
                        closed = True, 
                        note = '0', 
                        balance = 56, 
                        cleared_balance = 56, 
                        uncleared_balance = 56, 
                        transfer_payee_id = '0', 
                        deleted = True, )
                    ], 
                payees = [
                    ynab_api.models.payee.Payee(
                        id = '0', 
                        name = '0', 
                        transfer_account_id = '0', 
                        deleted = True, )
                    ], 
                payee_locations = [
                    ynab_api.models.payee_location.PayeeLocation(
                        id = '0', 
                        payee_id = '0', 
                        latitude = '0', 
                        longitude = '0', 
                        deleted = True, )
                    ], 
                category_groups = [
                    ynab_api.models.category_group.CategoryGroup(
                        id = '0', 
                        name = '0', 
                        hidden = True, 
                        deleted = True, )
                    ], 
                categories = [
                    ynab_api.models.category.Category(
                        id = '0', 
                        category_group_id = '0', 
                        name = '0', 
                        hidden = True, 
                        original_category_group_id = '0', 
                        note = '0', 
                        budgeted = 56, 
                        activity = 56, 
                        balance = 56, 
                        goal_type = 'TB', 
                        goal_creation_month = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        goal_target = 56, 
                        goal_target_month = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        goal_percentage_complete = 56, 
                        deleted = True, )
                    ], 
                months = [
                    null
                    ], 
                transactions = [
                    ynab_api.models.transaction_summary.TransactionSummary(
                        id = '0', 
                        date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        amount = 56, 
                        memo = '0', 
                        cleared = 'cleared', 
                        approved = True, 
                        flag_color = 'red', 
                        account_id = '0', 
                        payee_id = '0', 
                        category_id = '0', 
                        transfer_account_id = '0', 
                        transfer_transaction_id = '0', 
                        matched_transaction_id = '0', 
                        import_id = '0', 
                        deleted = True, )
                    ], 
                subtransactions = [
                    ynab_api.models.sub_transaction.SubTransaction(
                        id = '0', 
                        transaction_id = '0', 
                        amount = 56, 
                        memo = '0', 
                        payee_id = '0', 
                        payee_name = '0', 
                        category_id = '0', 
                        category_name = '0', 
                        transfer_account_id = '0', 
                        deleted = True, )
                    ], 
                scheduled_transactions = [
                    ynab_api.models.scheduled_transaction_summary.ScheduledTransactionSummary(
                        id = '0', 
                        date_first = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        date_next = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        frequency = 'never', 
                        amount = 56, 
                        memo = '0', 
                        flag_color = 'red', 
                        account_id = '0', 
                        payee_id = '0', 
                        category_id = '0', 
                        transfer_account_id = '0', 
                        deleted = True, )
                    ], 
                scheduled_subtransactions = [
                    ynab_api.models.scheduled_sub_transaction.ScheduledSubTransaction(
                        id = '0', 
                        scheduled_transaction_id = '0', 
                        amount = 56, 
                        memo = '0', 
                        payee_id = '0', 
                        category_id = '0', 
                        transfer_account_id = '0', 
                        deleted = True, )
                    ]
            )
        else :
            return BudgetDetailAllOf(
        )

    def testBudgetDetailAllOf(self):
        """Test BudgetDetailAllOf"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
