# coding: utf-8

"""
    YNAB API Endpoints

    Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import ynab_api
from ynab_api.models.scheduled_transaction_summary import ScheduledTransactionSummary  # noqa: E501
from ynab_api.rest import ApiException

class TestScheduledTransactionSummary(unittest.TestCase):
    """ScheduledTransactionSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ScheduledTransactionSummary
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = ynab_api.models.scheduled_transaction_summary.ScheduledTransactionSummary()  # noqa: E501
        if include_optional :
            return ScheduledTransactionSummary(
                id = '0', 
                date_first = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                date_next = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                frequency = 'never', 
                amount = 56, 
                memo = '0', 
                flag_color = 'red', 
                account_id = '0', 
                payee_id = '0', 
                category_id = '0', 
                transfer_account_id = '0', 
                deleted = True
            )
        else :
            return ScheduledTransactionSummary(
                id = '0',
                date_first = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                date_next = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                frequency = 'never',
                amount = 56,
                account_id = '0',
                deleted = True,
        )

    def testScheduledTransactionSummary(self):
        """Test ScheduledTransactionSummary"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
