"""
    YNAB API Endpoints

    Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import ynab_api
from ynab_api.api.months_api import MonthsApi  # noqa: E501


class TestMonthsApi(unittest.TestCase):
    """MonthsApi unit test stubs"""

    def setUp(self):
        self.api = MonthsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_budget_month(self):
        """Test case for get_budget_month

        Single budget month  # noqa: E501
        """
        pass

    def test_get_budget_months(self):
        """Test case for get_budget_months

        List budget months  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
