"""
    YNAB API Endpoints

    Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

import ynab_api
from ynab_api.model.transactions_import_response_data import TransactionsImportResponseData

globals()['TransactionsImportResponseData'] = TransactionsImportResponseData
from ynab_api.model.transactions_import_response import TransactionsImportResponse


class TestTransactionsImportResponse(unittest.TestCase):
    """TransactionsImportResponse unit test stubs"""
    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionsImportResponse(self):
        """Test TransactionsImportResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TransactionsImportResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
